name: Deploy to Prod

on:
  push:
    branches:
      - prod

env:
  AWS_REGION: us-east-1
  S3_BUCKET: tripshred
  DISTRIBUTION_ID: E2ORLFWI6KM97M

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          check-latest: true

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }} 

      - name: Sync “tripshred” to S3 root
        run: aws s3 sync dist/tripshred s3://${{ env.S3_BUCKET }}/ 

      - name: Sync “crazeoh” subpath
        run: aws s3 sync dist/crazeoh s3://${{ env.S3_BUCKET }}/crazeoh/ 

      - name: Sync “spooky” subpath
        run: aws s3 sync dist/spooky s3://${{ env.S3_BUCKET }}/spooky/ 

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"
