name: Deploy to Prod

on:
  workflow_dispatch: {}    # manual trigger
  push:
    branches:
      - prod

env:
  AWS_REGION: us-east-1
  S3_BUCKET: tripshred
  DISTRIBUTION_ID: E2ORLFWI6KM97M

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout with LFS enabled and full history
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true            # fetch Git LFS files :contentReference[oaicite:5]{index=5}
          fetch-depth: 0       # fetch all history :contentReference[oaicite:6]{index=6}

      # 2. Ensure LFS pointers are resolved (optional)
      - name: Pull LFS objects
        run: git lfs pull    # replace any remaining pointers :contentReference[oaicite:7]{index=7}

      # 3. Build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          check-latest: true

      - name: Install dependencies & build
        run: |
          npm i
          npm run build

      # 4. AWS creds (via IAM user secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      # 5. Sync to S3 (no --delete)
      - name: Sync “tripshred” to S3 root
        run: aws s3 sync dist/tripshred s3://${{ env.S3_BUCKET }}/

      - name: Sync “crazeoh” subpath
        run: aws s3 sync dist/crazeoh s3://${{ env.S3_BUCKET }}/crazeoh/

      - name: Sync “loh” subpath
        run: aws s3 sync dist/loh s3://${{ env.S3_BUCKET }}/loh/

      # 6. Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"
