name: Deploy to Prod

on:
  workflow_dispatch: {}  # manual trigger
  push:
    branches:
      - prod

permissions:
  id-token: write           # required for OIDC-based assume-role :contentReference[oaicite:7]{index=7}
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: tripshred
  DISTRIBUTION_ID: E2ORLFWI6KM97M

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # latest v4 checkout :contentReference[oaicite:8]{index=8}

      - name: Setup Node.js
        uses: actions/setup-node@v4  # setup-node v4 :contentReference[oaicite:9]{index=9}
        with:
          node-version: '22.x'       # Node 22 LTS :contentReference[oaicite:10]{index=10}
          check-latest: true         # enable caching & latest patch

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # v4 with OIDC support :contentReference[oaicite:11]{index=11}
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Sync Tripshred to S3
        run: aws s3 sync dist/tripshred s3://${{ env.S3_BUCKET }}/  # AWS CLI s3 sync :contentReference[oaicite:12]{index=12}

      - name: Sync CrazeOh to S3
        run: aws s3 sync dist/crazeoh s3://${{ env.S3_BUCKET }}/crazeoh/

      - name: Sync Spooky to S3
        run: aws s3 sync dist/spooky s3://${{ env.S3_BUCKET }}/spooky/

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"               # invalidate all paths :contentReference[oaicite:13]{index=13}
