name: PR Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Pull LFS objects
        run: git lfs pull
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          check-latest: true
      - name: Install dependencies
        run: npm i
      - name: Run vitest
        run: npx vitest run
